name: Build Docker Image 

on: workflow_dispatch

jobs:
  expressions:
    runs-on: ubuntu-latest 
    steps: 
      - name: Get Expressions 
        run: echo $(github.com)  
  build:
    runs-on: ubuntu-latest 
    steps:

      - name: Code Checkout 
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  
